# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/882/bin/cmake

# The command to remove a file.
RM = /snap/cmake/882/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/workspace/mycompiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/workspace/mycompiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/882/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/882/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/workspace/mycompiler/CMakeFiles /home/ubuntu/workspace/mycompiler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/workspace/mycompiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/AST.o: src/AST.cpp.o
.PHONY : src/AST.o

# target to build an object file
src/AST.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AST.cpp.o
.PHONY : src/AST.cpp.o

src/AST.i: src/AST.cpp.i
.PHONY : src/AST.i

# target to preprocess a source file
src/AST.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AST.cpp.i
.PHONY : src/AST.cpp.i

src/AST.s: src/AST.cpp.s
.PHONY : src/AST.s

# target to generate assembly for a file
src/AST.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/AST.cpp.s
.PHONY : src/AST.cpp.s

src/RA.o: src/RA.cpp.o
.PHONY : src/RA.o

# target to build an object file
src/RA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/RA.cpp.o
.PHONY : src/RA.cpp.o

src/RA.i: src/RA.cpp.i
.PHONY : src/RA.i

# target to preprocess a source file
src/RA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/RA.cpp.i
.PHONY : src/RA.cpp.i

src/RA.s: src/RA.cpp.s
.PHONY : src/RA.s

# target to generate assembly for a file
src/RA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/RA.cpp.s
.PHONY : src/RA.cpp.s

src/TAC.o: src/TAC.cpp.o
.PHONY : src/TAC.o

# target to build an object file
src/TAC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/TAC.cpp.o
.PHONY : src/TAC.cpp.o

src/TAC.i: src/TAC.cpp.i
.PHONY : src/TAC.i

# target to preprocess a source file
src/TAC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/TAC.cpp.i
.PHONY : src/TAC.cpp.i

src/TAC.s: src/TAC.cpp.s
.PHONY : src/TAC.s

# target to generate assembly for a file
src/TAC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/TAC.cpp.s
.PHONY : src/TAC.cpp.s

src/gen.o: src/gen.cpp.o
.PHONY : src/gen.o

# target to build an object file
src/gen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/gen.cpp.o
.PHONY : src/gen.cpp.o

src/gen.i: src/gen.cpp.i
.PHONY : src/gen.i

# target to preprocess a source file
src/gen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/gen.cpp.i
.PHONY : src/gen.cpp.i

src/gen.s: src/gen.cpp.s
.PHONY : src/gen.s

# target to generate assembly for a file
src/gen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/gen.cpp.s
.PHONY : src/gen.cpp.s

src/global.o: src/global.cpp.o
.PHONY : src/global.o

# target to build an object file
src/global.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/global.cpp.o
.PHONY : src/global.cpp.o

src/global.i: src/global.cpp.i
.PHONY : src/global.i

# target to preprocess a source file
src/global.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/global.cpp.i
.PHONY : src/global.cpp.i

src/global.s: src/global.cpp.s
.PHONY : src/global.s

# target to generate assembly for a file
src/global.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/global.cpp.s
.PHONY : src/global.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parser.o: src/parser.cpp.o
.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/scan.o: src/scan.cpp.o
.PHONY : src/scan.o

# target to build an object file
src/scan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/scan.cpp.o
.PHONY : src/scan.cpp.o

src/scan.i: src/scan.cpp.i
.PHONY : src/scan.i

# target to preprocess a source file
src/scan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/scan.cpp.i
.PHONY : src/scan.cpp.i

src/scan.s: src/scan.cpp.s
.PHONY : src/scan.s

# target to generate assembly for a file
src/scan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/scan.cpp.s
.PHONY : src/scan.cpp.s

src/symbol.o: src/symbol.cpp.o
.PHONY : src/symbol.o

# target to build an object file
src/symbol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/symbol.cpp.o
.PHONY : src/symbol.cpp.o

src/symbol.i: src/symbol.cpp.i
.PHONY : src/symbol.i

# target to preprocess a source file
src/symbol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/symbol.cpp.i
.PHONY : src/symbol.cpp.i

src/symbol.s: src/symbol.cpp.s
.PHONY : src/symbol.s

# target to generate assembly for a file
src/symbol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/symbol.cpp.s
.PHONY : src/symbol.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... src/AST.o"
	@echo "... src/AST.i"
	@echo "... src/AST.s"
	@echo "... src/RA.o"
	@echo "... src/RA.i"
	@echo "... src/RA.s"
	@echo "... src/TAC.o"
	@echo "... src/TAC.i"
	@echo "... src/TAC.s"
	@echo "... src/gen.o"
	@echo "... src/gen.i"
	@echo "... src/gen.s"
	@echo "... src/global.o"
	@echo "... src/global.i"
	@echo "... src/global.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/scan.o"
	@echo "... src/scan.i"
	@echo "... src/scan.s"
	@echo "... src/symbol.o"
	@echo "... src/symbol.i"
	@echo "... src/symbol.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

