LMBRACKETS, RMBRACKETS, LBBRACKETS, RBBRACKETS, NE, AND, LE, EQ, GE,
    LBLOCK_NOTE, RBLOCK_NOTE, SEMICOLON, LINE_NOTE, IF, OR, INT, CONSTINT,
    ARRAY, ELSE, VOID, BREAK, CONST, WHILE, CONTINUE, RETURN, FILEEND, ASSIGN,
    UNDEFINE
